name: PR-checks
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint using black and flake8
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64' # (x64 or x86)
      - run: pip install black==20.8b1 flake8
      # Just checks all the files in the repo. Could be improved by only checking for files that were changed
      - run: black -l 120 --check .
      - name: flake8
        # Run even if black fails
        if: always()
        run: flake8 --max-line-length=120 --ignore=E203 .

  large-file-size-warning:
    runs-on: ubuntu-latest
    name: Check that no large files have been added
    steps:
      - uses: actions/checkout@v1
      - uses: ppremk/lfs-warning@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filesizelimit: '524288' # 512Kb

  build-linux:
    name: Build linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64' # (x64 or x86)
      # Needed for bleak tests
      - name: apt update
        run: sudo apt-get update
      - name: Install Bluez on Ubuntu
        run: sudo apt-get install -y bluez
      - name: pip install
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest .
